#!/bin/bash

set -e

PROJECT_ROOT="$(dirname "$0")"
FRONTEND="$PROJECT_ROOT/dex-tracker-frontend"
BACKEND="$PROJECT_ROOT/dex-tracker-backend"
BACKEND_RESOURCES="$BACKEND/src/main/resources"

rm -rf $BACKEND_RESOURCES/assets
mkdir $BACKEND_RESOURCES/assets
mkdir $BACKEND_RESOURCES/assets/static
mkdir $BACKEND_RESOURCES/assets/static/icons
mkdir $BACKEND_RESOURCES/assets/templates/

npm install --prefix $FRONTEND
npm run build --prefix $FRONTEND

find "$BACKEND_RESOURCES/assets/static/dex-tracker" -name '*.png' -exec mv {} $BACKEND_RESOURCES/assets/static/icons \;
find "$BACKEND_RESOURCES/assets/static/dex-tracker" -type f -name '*.css' | xargs sed -i -e 's/static/icons/g'

find "$BACKEND_RESOURCES/assets/static/dex-tracker" -name 'index.html' -exec mv {} $BACKEND_RESOURCES/assets/templates/index.ftl \;

if [ ! -d pokemon-sprites/ ]; then
  git clone git@github.com:aleperaltabazas/pokemon-sprites
fi

git -C pokemon-sprites pull
cp -r pokemon-sprites/sprites/ $BACKEND_RESOURCES/assets/static/sprites
cp -r pokemon-sprites/icons/* $BACKEND_RESOURCES/assets/static/icons

