#!/bin/bash

set -e

PROJECT_ROOT="$(dirname "$0")"
FRONTEND="$PROJECT_ROOT/dex-tracker-frontend"
BACKEND="$PROJECT_ROOT/dex-tracker-backend"
BACKEND_RESOURCES="$BACKEND/src/main/resources"

rm -rf $BACKEND_RESOURCES/assets
mkdir $BACKEND_RESOURCES/assets
mkdir $BACKEND_RESOURCES/assets/templates/

npm install --prefix $FRONTEND
npm run build --prefix $FRONTEND

find "$BACKEND_RESOURCES/assets/static/dex-tracker" -name 'index.html' -exec mv {} $BACKEND_RESOURCES/assets/templates/index.ftl \;

if [ ! -d "assets/" ]; then
    mkdir "assets"
fi

if [ ! -d "assets/sprites/" ]; then
    mkdir "sprites"
    echo "Downloading sprites..."
    dex-sprites-dump 1 "assets/sprites"
    dex-sprites-dump 2 "assets/sprites"
    dex-sprites-dump 3 "assets/sprites"
    dex-sprites-dump 4 "assets/sprites"
    dex-sprites-dump 5 "assets/sprites"
fi

cp -r "assets/sprites" "$BACKEND_RESOURCES/assets/static/dex-tracker"
