#!/bin/bash

set -e

PROJECT_ROOT="$(dirname "$0")"
FRONTEND="$PROJECT_ROOT/dex-tracker-frontend"
BACKEND="$PROJECT_ROOT/dex-tracker-backend"
BACKEND_RESOURCES="$BACKEND/src/main/resources"

rm -rf $BACKEND_RESOURCES/assets
mkdir $BACKEND_RESOURCES/assets
mkdir $BACKEND_RESOURCES/assets/templates/

npm install --prefix $FRONTEND
npm run build --prefix $FRONTEND

find "$BACKEND_RESOURCES/assets/static/dex-tracker" -name 'index.html' -exec mv {} $BACKEND_RESOURCES/assets/templates/index.ftl \;
