#!/bin/bash

FRONTEND="dex-tracker-frontend"
BACKEND="dex-tracker-backend"
BACKEND_RESOURCES=$BACKEND/src/main/resources
ARTIFACT="escuelita"

npm install --prefix $FRONTEND
npm run build --prefix $FRONTEND

rm -rf $BACKEND_RESOURCES/static

mkdir $BACKEND_RESOURCES/static

cp -r $FRONTEND/build/index.html $BACKEND_RESOURCES/static/index.html
cp -r $FRONTEND/build/static/* $BACKEND_RESOURCES/static/

find $BACKEND_RESOURCES -type f -print0 | xargs -0 sed -i -e 's/\/static\//\//g'

