#!/bin/bash

set -e

ENV=$1
FRONTEND="dex-tracker-frontend"
BACKEND="dex-tracker-backend"
BACKEND_RESOURCES=$BACKEND/src/main/resources

cp -r $BACKEND/environments/$ENV/* $BACKEND_RESOURCES/
cp -r $FRONTEND/environments/$ENV/config.ts $FRONTEND/src/config.ts

./build-statics

