#!/bin/bash

set -e

if [ "$#" -ne 1 ]; then
    echo "Error: Illegal number of parameters"
    echo "Run like ./deploy <version>"
    exit 1
fi

ENV=prod
VERSION=$1
FRONTEND="dex-tracker-frontend"
BACKEND="dex-tracker-backend"
BACKEND_RESOURCES=$BACKEND/src/main/resources

mkdir bk
mv $BACKEND_RESOURCES/application.conf bk/application.conf
mv $BACKEND_RESOURCES/sensitive.conf bk/sensitive.conf
mv $BACKEND_RESOURCES/logback.xml bk/logback.xml
mv $FRONTEND/src/config.ts bk/config.ts

mvn --batch-mode -f $BACKEND/pom.xml clean test
mvn --batch-mode -f $BACKEND/pom.xml versions:set -DnewVersion="$VERSION-SNAPSHOT" -Dmaven.test.skip=true -DgenerateBackupPoms=false

git add .
git commit -m "[RELEASE] Version $VERSION"
git tag $VERSION
git push origin HEAD
git push --tags

./build $ENV

mvn -f $BACKEND/pom.xml heroku:deploy -Dmaven.test.skip=true

mv bk/application.conf $BACKEND_RESOURCES/application.conf
mv bk/sensitive.conf $BACKEND_RESOURCES/sensitive.conf
mv bk/logback.xml $BACKEND_RESOURCES/logback.xml
mv bk/config.ts $FRONTEND/src/config.ts
rmdir bk

mvn --batch-mode -f $BACKEND/pom.xml clean

